language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - cd authapi
  - python manage.py syncdb --noinput
  - python manage.py loaddata initial
  - python manage.py test
  - coverage run --source='.' manage.py test
after_success: coveralls
